# Help: rename the adject docker-compose.override.example.yml file to docker-compose.override.yml
#       then in the override file uncomment the environment tag for the collectors you want to
#       run. Then add the environment vars you want to use.
version: '3'

services:
  db:
    build: db
    ports:
      - "27017:27017"
  api:
    image: thoughtworksindia/hygieia-api
    env_file:
    - api/config.env
    depends_on:
      - db
  ui:
    image: thoughtworksindia/hygieia-ui
    env_file:
    - ui/config.env
    depends_on:
      - api
    ports:
      - "8090:80"

